#!/bin/env bash
# -*- coding: utf-8 -*-
## @File   : initial_php.bash
## @Author : sensor-dream (sensor-dream@sensor-dream.ru)
## @Link   : https://sensor-dream.ru
## @Date   : 2019-1-10 17:28:19

#
#   Декларируем имя файла
#

declare -rx www_initial_php_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $www_initial_php_script_source";

function initial_php(){

  check_root;

  . "${main_project_path}/pkg/programming/php";

  local php_ini="/etc/php.ini";

  if [[ -f "$php_ini" ]];then
    if ! grep -q -E "^expose_php = Off" $php_ini; then
      sed -i -r 's/^[#]?expose_php =.*$/expose_php = Off/g' $php_ini;
      echo_w "expose_php in php.ini prepared";
    else
      echo_w "expose_php in php.ini already prepared";
    fi
    if ! grep -q -E "^upload_max_filesize = 50M" $php_ini; then
      sed -i -r 's/^[#]?upload_max_filesize =.*$/upload_max_filesize = 50M/g' $php_ini;
      echo_w "upload_max_filesize in php.ini prepared";
    else
      echo_w "upload_max_filesize in php.ini already prepared";
    fi
    if ! grep -q -E  "^post_max_size = 100M" $php_ini; then
      sed -i -r 's/^[#]?post_max_size =.*$/post_max_size = 100M/g' $php_ini;
      echo_w "post_max_size in php.ini prepared";
    else
      echo_w "post_max_size in php.ini already prepared";
    fi
  fi

  # systemctl_activate_and_start_or_restart_service php-fpm;

}

initial_php "$@";
