#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : mailer_sample_json
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 03.08.2019, 22:01:54

#
#   Декларируем имя файла
#

declare -rx version_control_system_phabricator_mailer_sample_json_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $version_control_system_phabricator_mailer_sample_json_script_source)";

cat << EOF > "${main_project_path}/security_file/phabricator/mailer.json";
[
  {
    "key": "phabricator-mailer",
    "type": "smtp",
    "options": {
      "host": "${mail_host}",
      "port": ${mail_port},
      "user": "${mail_user}",
      "password": "${mail_pass}",
      "protocol": "ssl",
      "message-id": true
    }
  }
]

EOF
