#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : phabricator_phd_service
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 03.08.2019, 22:10:44

#
#   Декларируем имя файла
#

declare -rx version_control_system_phabricator_phabricator_phd_service_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $version_control_system_phabricator_phabricator_phd_service_script_source)";

cat<<EOF > '/usr/lib/systemd/system/phabricator-phd.service';
[Unit]

Description=Phabricator Background Daemons
After=network.target httpd.service php-fpm.service mysql.service

[Service]

User=${phd_user}
Group=${phd_user}

Type=forking

ExecStart=${phabricator_www_path}/phabricator/bin/phd start
ExecStop=${phabricator_www_path}/phabricator/bin/phd stop
ExecReload=/bin/kill -HUP $
KillMode=process
Restart=on-failure
RestartSec=42s

[Install]
WantedBy=multi-user.target

EOF
