#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : dev
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 26.10.2019, 11:08:25

#
#   Декларируем имя файла
#

declare -rx dev_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${dev_script_source})";

function install_dev(){

  #
  # Instalation system package
  #
  local install_pkg=(\
'kernel-devel' \
'kernel-headers' \
'kernel-cross-headers' \
'kernel-modules' \
'kernel-modules-extra' \
'kernel-tools' \
'kernel-tools-libs' \
'kernel-tools-libs-devel' \
'dkms' \
'elfutils-libelf-devel' \
'zlib-devel' \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  #
  #
  #
  install_pkg=(\
);

  pkg -a "$@" -- "${install_pkg[*]}";

  #
  #
  #
  install_pkg+=(\

);

  pkg -a "$@" -- "${install_pkg[*]}";

  #
  #
  #
  install_pkg+=(\

);

  pkg -a "$@" -- "${install_pkg[*]}";
  
  #
  #
  #
  install_pkg+=(\

);

  pkg -a "$@" -- "${install_pkg[*]}";

  #
  #
  #  
  install_pkg+=(\

);

  pkg -a "$@" -- "${install_pkg[*]}";

  #
  #
  #
  install_pkg+=(\

);

  pkg -a "$@" -- "${install_pkg[*]}";

  #
  #
  #
  install_pkg+=(\

);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_dev_script_source(){

  echo_m "Initialise main function of dev script source";

  . "${main_project_path}/preparation/network_ifaces";

  install_dev "$@";

}

main_dev_script_source "$@";
