#!/bin/env bash
# -*- coding: utf-8 -*-
## @File   : gitkraken.bash
## @Author : sensor-dream (sensor-dream@sensor-dream.ru)
## @Link   : https://sensor-dream.ru
## @Date   : 2019-1-8 22:57:42

#
#   Декларируем имя файла
#

declare -rx version_control_system_gitkraken_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $version_control_system_gitkraken_script_source";

#   GitKraken - The legendary Git GUI client for Windows, Mac and Linux.
#   перед установкой gitkraken выполнить ./rpm/compat_libcurl_gnutls

function gitkraken() {

  check_user;

}

if [[ -z $(check_install_packages compat-libcurl-gnutls) ]]; then
  . "${main_project_path}/pkg/compat_libcurl_gnutls";
fi


gitkraken;
