#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : pdns
## @Author :
## @Email  :
## @Site   :
## @Date   : 02.05.2019, 0:01:38

#
#   Декларируем имя файла
#

declare -rx dns_pdns_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $dns_pdns_script_source)";


function main_dns_pdns_script_source(){

  echo_m "Initialise main function";

  check_root;

  local install_pkg=(\
'pdns pdns-backend-geoip pdns-backend-lua pdns-backend-mysql pdns-backend-pipe pdns-backend-remote pdns-backend-sqlite pdns-tools' \
' poweradmin' \
);


  pkg $@ ${install_pkg[*]};

}

main_dns_pdns_script_source "$@";