#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : atom
## @Author :
## @Email  :
## @Site   :
## @Date   : 10.05.2019, 18:46:11

#
#   Декларируем имя файла
#

declare -rx pkg_repo_atom_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_repo_atom_script_source)";


function main_pkg_repo_atom_script_source(){

  check_root;

  echo_m "Initialise main function";

  if [[ ! -f '/etc/yum.repos.d/atom.repo' ]]; then
    rpm --import https://packagecloud.io/AtomEditor/atom/gpgkey;

    sh -c 'echo -e "[Atom]\nname=Atom Editor\nbaseurl=https://packagecloud.io/AtomEditor/atom/el/7/\$basearch\nenabled=1\ngpgcheck=0\nrepo_gpgcheck=1\ngpgkey=https://packagecloud.io/AtomEditor/atom/gpgkey" > /etc/yum.repos.d/atom.repo';

  fi

}

main_pkg_repo_atom_script_source "$@";
