#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : percona_software
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 11.08.2019, 15:29:00

#
#   Декларируем имя файла
#

declare -rx pkg_repo_percona_software_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${pkg_repo_percona_software_script_source})";

function install_pkg_repo_percona_software(){

  # https://www.percona.com/doc/percona-server-for-mongodb

  local install_pkg=(\
'https://repo.percona.com/yum/percona-release-latest.noarch.rpm' \
);

  if [[ ! -f '/etc/yum.repos.d/percona-original-release.repo' ]]; then
    pkg -a "$@" -- "${install_pkg[*]}";
    sed -i -r "s/$releasever/${main_releasever_centos_for_dnf}/g" '/etc/yum.repos.d/percona-original-release.repo';
    sed -i -r 's/^gpgcheck.*$/gpgcheck = 0/g' '/etc/yum.repos.d/percona-original-release.repo';
  fi

}

function main_pkg_repo_percona_software_script_source(){

  echo_m "Initialise main function of percona_software script source";

  install_pkg_repo_percona_software "$@";

}

main_pkg_repo_percona_software_script_source "$@";
