#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : sublimetext
## @Author :
## @Email  :
## @Site   :
## @Date   : 10.05.2019, 19:17:24

#
#   Декларируем имя файла
#

declare -rx pkg_repo_sublimetext_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_repo_sublimetext_script_source)";


function main_pkg_repo_sublimetext_script_source(){

  check_root;

  echo_m "Initialise main function";

  if [[ ! -f '/etc/yum.repos.d/sublime-text.repo' ]]; then

    rpm -v --import 'https://download.sublimetext.com/sublimehq-rpm-pub.gpg';

    dnf config-manager --add-repo 'https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo';

    # dnf config-manager --add-repo 'https://download.sublimetext.com/rpm/dev/x86_64/sublime-text.repo';

  fi

}

main_pkg_repo_sublimetext_script_source "$@";
