#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : preparation
## @Author : sensor-dream (SDBS)
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 06.05.2019, 19:59:16

#
#   Декларируем имя файла
#

declare -rx docker_preparation_script_source="$BASH_SOURCE"

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  echo "Скрипт запускается из ${main_run_script_path}"
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd "${main_run_script_path}"
        check=0
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)"
        . "$main_project_path/main.cfg"
      fi
      cd "${main_run_script_path}"
    fi
  done
fi

echo_w "Подключаем $(readlink -m $docker_preparation_script_source)"

function main_docker_preparation_script_source() {

  echo_m "Initialise main function"

  echo_m "Remove current docker"

  dnf remove docker \
    docker-client \
    docker-client-latest \
    docker-common \
    docker-latest \
    docker-latest-logrotate \
    docker-logrotate \
    docker-selinux \
    docker-engine-selinux \
    docker-engine

  # . "$main_project_path/pkg/docker_ce"

}

main_docker_preparation_script_source "$@"
