#!/bin/env bash
#
# -*- coding: utf-8 -*-
#
## @File   : generate_wildcard_certificate_for_main_domain
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 16.07.2019, 15:04:41

#
#   Декларируем имя файла
#

declare -rx www_generate_wildcard_certificate_for_main_domain_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $www_generate_wildcard_certificate_for_main_domain_script_source)";

function install_www_generate_wildcard_certificate_for_main_domain(){

  local install_pkg=(\

);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_www_generate_wildcard_certificate_for_main_domain_script_source(){

  echo_m "Initialise main function of generate_wildcard_certificate_for_main_domain script source";

  . "${main_project_path}/www/initial_certbot";

  generate_wildcard_certificate_for_main_domain -- "$@";
  # generate_certivecate_for_main_domain_and_also_using_csr -- "$@";

}

main_www_generate_wildcard_certificate_for_main_domain_script_source "$@";
