#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : initial_fcgiwrap
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 01.08.2019, 16:24:53

#
#   Декларируем имя файла
#

declare -rx www_initial_fcgiwrap_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $www_initial_fcgiwrap_script_source)";

function install_www_initial_fcgiwrap(){

  local install_pkg=(\
fcgiwrap \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_initial_www_fcgiwrap_script_source(){

  echo_m "Initialise main function of initial_fcgiwrap script source";

}

main_initial_www_fcgiwrap_script_source "$@";
