#!/bin/env bash
# -*- coding: utf-8 -*-
## @File   : nodejs.bash
## @Author : sensor-dream (sensor-dream@sensor-dream.ru)
## @Link   : https://sensor-dream.ru
## @Date   : 2019-1-15 17:01:11

#
#   Декларируем имя файла
#

declare -rx pkg_programming_node_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем ${pkg_programming_node_script_source}";

function install_pkg_programming_nodejs(){

  check_root;

  local install_pkg=(\
npm \
nodejs \
);

  if [[ "$1" == "-u" ]];then
    remove_packages "${install_pkg[*]}";
  else
    if [[ -z "$(check_install_packages 'nodejs')"  ]]; then
      install_packages "${install_pkg[*]}";
    else 
      echo_m "${install_pkg[@]} already install";
    fi
  fi

}

install_pkg_programming_nodejs $1;
