#!/bin/env bash
# -*- coding: utf-8 -*-
## @File   : php.bash
## @Author : sensor-dream (sensor-dream@sensor-dream.ru)
## @Link   : https://sensor-dream.ru
## @Date   : 2019-1-10 17:28:19

#
#   Декларируем имя файла
#

declare -rx pkg_programming_php_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $pkg_programming_php_script_source";

function install_pkg_programming_php(){

  check_root;

  local install_pkg=(\
php php-fpm php-phpunit-PHPUnit php-pear php-pear-MDB2 \
php-pear-MDB2-Driver-mysqli php-pecl-memcache php-pecl-memcached \
php-pecl-apcu php-pecl-apcu-bc php-devel php-pecl-apcu-devel \
php-pear-PHP-CodeSniffer composer php-embedded \
php-domxml-php4-php5 php-masterminds-html5 \
php-pecl-krb5 php-pecl-krb5-devel php-phpunit-mock-objects5 php-phpunit-php-code-coverage5 \
php-sabre-event5 php-whitehat101-apr1-md5 php-pecl-mcrypt php-ldap \
php-cs-fixer php-pecl-yaml \
php-imap php-xmlrpc php-pear-CAS php-pclzip \
memcached \
libyaml libyaml-devel yamllint \
graphviz \
phpdoc \
doxygen \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  echo "Version PHP $(echo $(php -v) | awk '{ print $2}')";

}

install_pkg_programming_php "$@";
