#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : ruby
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 09.08.2019, 0:55:26

#
#   Декларируем имя файла
#

declare -rx pkg_programming_ruby_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "${main_cfg_script_source}" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "${main_project_path}/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${pkg_programming_ruby_script_source})";

function install_pkg_programming_ruby(){

  local install_pkg=(\
'ruby' \
'ruby-libs' \
'rubygem-bigdecimal' \
'rubygem-daemon_controller' \
'rubygem-did_you_mean' \
'rubygem-io-console' \
'rubygem-irb' \
'rubygem-json' \
'rubygem-openssl' \
'rubygem-psych' \
'rubygem-rack' \
'rubygem-rake' \
'rubygem-rdoc' \
'rubygems' \
'rubypick' \
'ruby-devel' \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  echo "Version RUBY $(echo $(ruby -v) | awk '{ print $2}')";

}

function main_pkg_programming_ruby_script_source(){

  echo_m "Initialise main function of ruby script source";

  install_pkg_programming_ruby;

}

main_pkg_programming_ruby_script_source "$@";
