#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : rust
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 25.07.2019, 1:44:38

#
#   Декларируем имя файла
#

declare -rx pkg_programming_rust_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_programming_rust_script_source)";

function install_pkg_programming_rust(){

  local install_pkg=(\
# Rust is a systems programming language that runs blazingly fast, prevents
# : segfaults, and guarantees thread safety.
# : This package includes the Rust compiler and documentation generator.
'rust rust-std-static rust-analysis rust-debugger-common rust-doc rust-gdb rust-lldb rust-packaging rust-src rustfmt' \
# Cargo is a tool that allows Rust projects to declare their various dependencies
#   : and ensure that you'll always get a repeatable build.
'cargo' \
# LLDB is a next generation, high-performance debugger. It is built as a set
# : of reusable components which highly leverage existing libraries in the
# : larger LLVM Project, such as the Clang expression parser and LLVM
# : disassembler.
'lldb' \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_pkg_programming_rust_script_source(){

  echo_m "Initialise main function of rust script source";

  install_pkg_programming_rust "$@";

}

main_pkg_programming_rust_script_source "$@";
