#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : rpl_substr_for_recursive_files
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 09.08.2019, 4:51:33

#
#   Декларируем имя файла
#

declare -rx lib_rpl_substr_for_recursive_files_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${lib_rpl_substr_for_recursive_files_script_source})";

function main_lib_rpl_substr_for_recursive_files_script_source(){

  echo_m "Initialise main function of rpl_substr_for_recursive_files script source";

  # find /mnt/sda/Development/repo_share/Fedora-post-Install -type f -name 'main.cfg' -exec sed -i -r 's/\$\(dirname \$\(readlink -m \$0\) \)/$(pwd)/g' {} \;
  # find /mnt/sda/Development/repo_share/Fedora-post-Install -type f -name '*' -exec sed -i -r 's/\$\(dirname \$\(readlink -m \$0\) \)/$(pwd)/g' {} \;
  # find /mnt/sda/Development/repo_share/Fedora-post-Install -type f -name '*' -exec sed -i -r 's/\$project_path\//${main_project_path}\//g' {} \;

}

main_lib_rpl_substr_for_recursive_files_script_source "$@";
