#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : for_user_golum
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 09.08.2019, 2:49:55

#
#   Декларируем имя файла
#

declare -rx version_control_system_gollum_for_user_golum_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "${main_cfg_script_source}" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "${main_project_path}/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${version_control_system_gollum_for_user_golum_script_source})";

function install_version_control_system_gollum_for_user_golum(){

  [[ -a ${gollum_git_repo_share} ]] && declare -rx gollum_git_repo_share="${1}";

  echo_w "${USER}";

    ## Installing Ruby with RVM
  cd;
  command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -;
  command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -;
  command curl -sSL https://get.rvm.io | bash -s stable --ruby

  source ~/.rvm/scripts/rvm;
  rvm install ruby;
  ruby --version;

  ## Install gollem
  gem install gollum puma asciidoctor creole org-ruby RedCloth;

  git init ~/${gollum_git_repo_share};

}

function main_version_control_system_gollum_for_user_golum_script_source(){

  echo_m "Initialise main function of for_user_golum script source";

  install_version_control_system_gollum_for_user_golum $@;

}

main_version_control_system_gollum_for_user_golum_script_source "$@";
