#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : upgrate
## @Author : sensor-dream (SDBS)
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 29.03.2019, 13:02:28

#
#   Декларируем имя файла
#

declare -rx preparation_upgrate_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $preparation_upgrate_script_source)";


function main_preparation_upgrate_script_source(){

  echo_m "Initialise main function";

  check_root;

  local install_pkg=(\
'python3-dnf-plugin-system-upgrade' \
'rpmconf' \
);

  install_packages "${install_pkg[*]}";

  dnf upgrade --refresh;

  echo -ne "Reboot system (n) (y/n): ";

  read key;

  if [[ $(validate_reply $key) -eq 1 ]]; then
    echo_w "Reebot system";
    systemctl reboot;
  fi

  if [[ $@ -gt $lsb_release_short ]]; then

    echo_m "$@ > $lsb_release_short is ok";

    ## dnf system-upgrade download --refresh --releasever="$@" --setopt="module_platform_id=platform:f$@" --setopt='keepcache=1' --skip-broken --best --allowerasing  --nogpgcheck -y;
    dnf system-upgrade download --refresh --releasever="$@" --setopt="module_platform_id=platform:f$@" --setopt='keepcache=1' --skip-broken --allowerasing  --nogpgcheck -y;

    rpm --import "/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$(($@ + 1))-primary";
    rpm --import "/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$@-primary";

    ## dnf system-upgrade reboot;
    ## dnf system-upgrade --skip-broken --best --allowerasing --nogpgcheck reboot;
    dnf system-upgrade --best --allowerasing --nogpgcheck reboot;
    ## dnf system-upgrade --nogpgcheck reboot;

  elif [[ $@ -eq $lsb_release_short ]]; then

    echo_m "$@ = $lsb_release_short";

    rpm --rebuilddb;

    ## dnf distro-sync --allowerasing;
    ## dnf distro-sync --releasever="$@" --setopt='deltarpm=0';
    dnf distro-sync --setopt='deltarpm=0' --releasever="$@" --setopt="module_platform_id=platform:f$@" --setopt='keepcache=1' --skip-broken --allowerasing --nogpgcheck -y
    rpmconf -a;
    dnf check;

    ## dnf remove $(dnf repoquery --extras --exclude=kernel,kernel-\*);

    echo_m "Прибираемся";
    dnf autoremove;

  else

    echo_w "$@ < $lsb_release_short";

  fi

}

main_preparation_upgrate_script_source "$@";