#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : variety_vallpaper_changer
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 29.08.2019, 17:44:09

#
#   Декларируем имя файла
#

declare -rx vallpapers_variety_vallpaper_changer_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${vallpapers_variety_vallpaper_changer_script_source})";

function install_vallpapers_variety_vallpaper_changer(){

  local install_pkg=(\
# Repository   : updates
# Summary      : Wallpaper changer that automatically downloads wallpapers
# URL          : https://github.com/varietywalls/variety
# Лицензия     : GPLv3
# Description  : Variety changes the desktop wallpaper on a regular basis,
# : using user-specified or automatically downloaded images.
# :
# : Variety sits conveniently as an indicator in the panel
# : and can be easily paused and resumed. The mouse wheel
# : can be used to scroll wallpapers back and forth until
# : you find the perfect one for your current mood.
# :
# : Apart from displaying images from local folders, several
# : different online sources can be used to fetch wallpapers
# : according to user-specified criteria.
# :
# : Variety can also automatically apply various fancy
# : filters to the displayed images - charcoal painting,
# : oil painting, heavy blurring, etc. - so that your
# : desktop is always fresh and unique.
'variety' \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_vallpapers_variety_vallpaper_changer_script_source(){

  echo_m "Initialise main function of vallpaper_changer script source";

  check_root;

  install_vallpapers_variety_vallpaper_changer "$@";

  if [[ -f "/home/${main_user}/.config/variety/variety.conf" ]]; then
    if ! grep -q -E "^clock_filter([ ]+)?=([ ]+)?.*0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %d %B' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %d %B'" "/home/${main_user}/.config/variety/variety.conf"; then

      sed -i "s/'%A, %B %d'/'%A, %d %B'/" "/home/${main_user}/.config/variety/variety.conf";

    fi
  fi

}

main_vallpapers_variety_vallpaper_changer_script_source "$@";
