#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : install
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream
## @Date   : 04.11.2019, 2:12:28

#
#   Декларируем имя файла
#

declare -rx blob_nvidia_install_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${blob_nvidia_install_script_source})";

function install_blob_nvidia_install(){

  local kernel=$(uname -r | awk -F. '{ print $1"."$2 }');

  if [[ ! -f "${main_project_path}/blob_nvidia/NVIDIA-Linux-x86_64-340.107-kernel-${kernel}-patched.run" ]]; then

    echo_w "Not file NVIDIA-Linux-x86_64-340.107-kernel-${kernel}-patched.run";

    exit 1;

  else

    bash ${main_project_path}/blob_nvidia/NVIDIA-Linux-x86_64-340.107-kernel-5.3-patched.run;

    if [[ ! -f "/home/${main_user}/.local/share/flatpak/exports/share/applications/nvidia-settings.desktop" ]]; then
      
      if [[ ! -d "/home/${main_user}/.local/share/flatpak/exports/share/applications" ]]; then
        
        mkdir -p "/home/${main_user}/.local/share/flatpak/exports/share/applications";

      fi

      cp '/root/.local/share/flatpak/exports/share/applications/nvidia-settings.desktop' "/home/${main_user}/.local/share/flatpak/exports/share/applications/nvidia-settings.desktop";

      chown -R ${main_user}.${main_user} "/home/${main_user}/.local/share/flatpak/exports/share/applications";

    fi
    

    systemctl set-default graphical.target;

    reboot;

  fi
  

}

function main_blob_nvidia_install_script_source(){

  check_root;

  echo_m "Initialise main function of install script source";

  install_blob_nvidia_install;

}

main_blob_nvidia_install_script_source "$@";
