#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : uninstall
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream
## @Date   : 04.11.2019, 13:32:19

#
#   Декларируем имя файла
#

declare -rx blob_nvidia_uninstall_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${blob_nvidia_uninstall_script_source})";

function uninstall_blob_nvidia_uninstall(){

  local install_pkg=(\
'xorg-x11-drv-nouveau' \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_blob_nvidia_uninstall_script_source(){

  echo_m "Initialise main function of uninstall script source";

  check_root;

  if [[ "$(systemctl get-default)" == "graphical.target" ]]
  then
    systemctl set-default multi-user.target;
    reboot;
  fi

  if [[ "$(systemctl get-default)" == "multi-user.target" ]]; then

    bash ${main_project_path}/blob_nvidia/NVIDIA-Linux-x86_64-340.107-kernel-5.3-patched.run --uninstall;

    if grep -qE "blacklist.*nouveau" '/etc/modprobe.d/blacklist.conf'; then

      local Num=($(sed -n "/blacklist.*nouveau/=" '/etc/modprobe.d/blacklist.conf'));
      
      local offset=0;

      for i in ${!Num[*]}; do
        
        sed -i -e $((${Num[$i]}-${offset}))"d;/^$/d" '/etc/modprobe.d/blacklist.conf';

        ((offset+=1))

      done

    fi

    if grep -q "rd.driver.blacklist=nouveau" /etc/default/grub; then

      cp "/etc/default/grub" "/etc/default/grub.nvidia.back";
      ## sed -i -e '/rd.driver.blacklist=nouveau/s/rd.driver.blacklist=nouveau nvidia-drm.modeset=1 //' '/etc/default/grub';
      sed -i -e '/rd.driver.blacklist=nouveau/s/rd.driver.blacklist=nouveau //' '/etc/default/grub';

    fi

    ## BIOS ##
    grub2-mkconfig -o /boot/grub2/grub.cfg;

    dnf install xorg-x11-drv-nouveau;

    ## Backup old initramfs nvidia image ##
    mv /boot/initramfs-$(uname -r).img /boot/initramfs-$(uname -r)-nvidia.img;
    
    ## Create new initramfs image ##
    dracut /boot/initramfs-$(uname -r).img $(uname -r);

    dnf reinstall xorg-\* mesa\* libglvnd\*;

    systemctl set-default graphical.target;
    reboot;

  fi

}

main_blob_nvidia_uninstall_script_source "$@";
