#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : install
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream
## @Date   : 04.11.2019, 21:26:23

#
#   Декларируем имя файла
#

declare -rx messenger_viber_install_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${messenger_viber_install_script_source})";

function install_messenger_viber_install(){

  local install_pkg=(\
flatpak \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo;

  wget https://sdk.gnome.org/keys/gnome-sdk.gpg;

  flatpak remote-add --gpg-import=gnome-sdk.gpg --if-not-exists gnome-apps https://sdk.gnome.org/repo-apps/;

  flatpak install flathub viber;

}

function main_messenger_viber_install_script_source(){

  echo_m "Initialise main function of install script source";

  chk_root;

  install_messenger_viber_install "$@";

}

main_messenger_viber_install_script_source "$@";
