#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : archiving_packs
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 12.05.2019, 3:14:53

#
#   Декларируем имя файла
#

declare -rx pkg_archiving_packs_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_archiving_packs_script_source)";


function main_pkg_archiving_packs_script_source(){

  echo_m "Initialise main function of archiving script source";

  check_root;

  local install_pkg=(\
#
#   file archiving program and tools, utility and library and encoding
#
gzip zlib zziplib zip unzip p7zip p7zip-plugins p7zip-gui p7zip-doc unar tar bzip2 lha lzma getdata-lzma libknet1-compress-lzma-plugin lzma-sdk lzma-sdk-devel lzma-sdk457-devel lzma-sdk457 xz-lzma-compat unace unrar zlib-devel zlib-static zlibrary zlibrary-devel xz-devel arj \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  install_pkg=(\
#   cabextract is a program which can extract files from cabinet (.cab) archives.
cabextract \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  install_pkg=(\
#   The GNU shar utilities for packaging and unpackaging shell archives
sharutils \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  install_pkg=(\
#   File Roller is an application for creating and viewing archives files, uch as tar or zip files.
file-roller \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  install_pkg=(\
# Ark is a program for managing various archive formats.
# :
# : Archives can be viewed, extracted, created and modified from within Ark.
# : The program can handle various formats such as tar, gzip, bzip2, zip,
# : rar and lha (if appropriate command-line programs are installed).
ark \
);

  pkg -a "$@" -- "${install_pkg[*]}";

install_pkg=(\
# Arc file archiver and compressor. Long since superseded by zip/unzip
# : but useful if you have old .arc files you need to unpack.
arc \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

main_pkg_archiving_packs_script_source "$@";
