#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: Pavel M. Teslenko
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © Pavel M. Teslenko. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: backup_utilities
## @Creation date file: 14.04.2020, 07:00:18

#
#   Декларируем имя файла
#

declare -rx backup_utilities_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo -e '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${backup_utilities_script_source})";

function install_backup_utilities(){

  local install_pkg=(\
# Краткое опис : Qt frontend for backintime
# URL          : https://github.com/bit-team/backintime
# Лицензия     : GPLv2+
# Описание     : BackInTime is a simple backup system for Linux inspired from
#              : “flyback project” and “TimeVault”. The backup is done by taking
#              : snapshots of a specified set of directories.
#              : 
#              : This package contains the Qt frontend of BackInTime.
'backintime-qt' \
'backintime-plugins' \
'backintime-common' \
# Краткое опис : Simple backup tool and frontend for duplicity
# URL          : https://gitlab.gnome.org/World/deja-dup
# Лицензия     : GPLv3+
# Описание     : Déjà Dup is a simple backup tool. It hides the complexity of doing backups the
#              : 'right way' (encrypted, off-site, and regular) and uses duplicity as the
#              : backend.
#              : 
#              : Features:
#              :  • Support for local, remote, or cloud backup locations (Amazon S3 or Rackspace)
#              :  • Securely encrypts and compresses your data
#              :  • Incrementally backs up, letting you restore from any particular backup
#              :  • Schedules regular backups
#              :  • Integrates well into your GNOME desktop
'deja-dup' \
'deja-dup-nautilus' \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_backup_utilities_script_source(){

  echo_m "Initialise main function of backup_utilities script source";

  install_backup_utilities "$@";

}

main_backup_utilities_script_source "$@";
