#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : backgrounds_pack
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 21.08.2019, 16:29:01

#
#   Декларируем имя файла
#

declare -rx pkg_backgrounds_pack_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${pkg_backgrounds_pack_script_source})";

function install_pkg_backgrounds_pack(){

  local install_pkg=(\
# Summary      : Fedora ${lsb_release_short} default wallpaper for Gnome and Cinnamon
# URL          : https://fedoraproject.org/wiki/F30_Artwork
# Лицензия     : CC-BY-SA
# Description  : This package contains Gnome/Cinnamon desktop wallpaper for the
# : Fedora 30 default theme.
"f${lsb_release_short}-backgrounds-gnome" \
"f${lsb_release_short}-backgrounds-extras-gnome" \
# 'arc-kde-wallpapers' \
# 'caja-wallpaper' \
# 'plasma-workspace-wallpapers' \
# 'texlive-wallpaper' \
# 'deepin-wallpapers' \
# 'elementary-wallpapers' \
# 'elementary-wallpapers-gnome' \
# 'kde-wallpapers' \
# 'kdeartwork-wallpapers' \
# 'lumina-desktop-wallpapers' \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_pkg_backgrounds_pack_script_source(){

  echo_m "Initialise main function of backgrounds_pack script source";

  install_pkg_backgrounds_pack "$@";

}

main_pkg_backgrounds_pack_script_source "$@";
