#!/bin/env bash

declare -rx pkg_compat_libcurl_gnutls_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $pkg_compat_libcurl_gnutls_script_source";

function compat_libcurl_gnutls() {

    check_user;

    if [[ -z "$(check_install_packages 'compat-libcurl-gnutls')"  ]]; then

        sudo install_packages rpm-build git;
        git clone https://github.com/EasyCoding/compat-libcurl-gnutls.git;
        cd compat-libcurl-gnutls;
        rpmbuild -bb compat-libcurl-gnutls.spec;
        sudo dnf -y install ~/rpmbuild/RPMS/$(uname -m)/compat-libcurl-gnutls-*.rpm;
        cd ../;
        rm -frd compat-libcurl-gnutls;
        rm -frd ~/rpmbuild;

    fi

}

compat_libcurl_gnutls;
