#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : de
## @Author : 
## @Email  : 
## @Site   : 
## @Date   : 23.10.2019, 2:46:28

#
#   Декларируем имя файла
#

declare -rx pkg_de_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${pkg_de_script_source})";

function install_pkg_de(){

  . "${main_project_path}/pkg/other_pack";

  local install_pkg=(\
'Deepin Desktop', \
'Administration Tools', \
'Common NetworkManager Submodules', \
'Core', \
'Deepin Desktop Applications', \
'Deepin Desktop Environment', \
'Dial-up Networking Support', \
'Fonts', \
'Guest Desktop Agents', \
'Hardware Support', \
'Input Methods', \
'Multimedia', \
'Printing Support', \
'Standard', \
'base-x', \
'3D Printing', \
'Cloud Management Tools', \
'Deepin Desktop Office', \
'Media packages for Deepin Desktop', \
'deepin-desktop' \
);

  # pkg -g "$@" -- "${install_pkg[*]}";

  install_pkg=(\
'Pantheon Desktop' \
);

  # pkg -g "$@" -- "${install_pkg[*]}";

  install_pkg=(\
'Рабочая среда MATE', \
'Приложения MATE' \
);

  pkg -g "$@" -- "${install_pkg[*]}";  

  install_pkg=(\
'Рабочая среда Cinnamon' \ 
);

  pkg -g "$@" -- "${install_pkg[*]}"; 

}

function main_pkg_de_script_source(){

  echo_m "Initialise main function of de script source";

  install_pkg_de "$@";

}

main_pkg_de_script_source "$@";
