#!/bin/env bash
# -*- coding: utf-8 -*-
## @File   : eclipse
## @Author : sensor-dream (SDBS)
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 07.02.2019, 14:48:04

#
#   Декларируем имя файла
#

declare -rx eclipse_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $eclipse_script_source";


function install_eclipse(){

  local install_pkg=(\
# Eclipse Java Development Tools.  This package is required to use Eclipse for
# : developing software written in the Java programming language.
'eclipse-jdt' \
'eclipse-nls-ru' \
);

  if [[ "$1" == "-u" ]];then
    remove_packages "${install_pkg[*]}";
  else
    if [[ -z "$(check_install_packages 'eclipse-jdt')"  ]]; then
      install_packages "${install_pkg[*]}";
    else
      echo_m "eclipse-jdt is install";
    fi
  fi

}

install_eclipse "$1";
