#!/bin/env bash
# -*- coding: utf-8 -*-
## @File   : eric_6_ide.bash
## @Author : sensor-dream (sensor-dream@sensor-dream.ru)
## @Link   : https://sensor-dream.ru
## @Date   : 2019-1-13 01:55:50

#
#   Декларируем имя файла
#

declare -rx pkg_eric_6_ide_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $pkg_eric_6_ide_script_source";

function eric_6_ide(){

  install_pkg=(\
# eric6 is a full featured Python IDE.
eric \
);

  if [[ "$1" == "-u" ]];then
    remove_packages "${install_pkg[*]}";
  else
    install_packages "${install_pkg[*]}";
  fi

}

eric_6_ide;
