#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : fonts_ms_2
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream
## @Date   : 04.11.2019, 21:22:24

#
#   Декларируем имя файла
#

declare -rx pkg_fonts_ms_2_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${pkg_fonts_ms_2_script_source})";

function install_pkg_fonts_ms_2(){

  local install_pkg=(\
curl cabextract xorg-x11-font-utils fontconfig \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  pkg -a -- https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm;

}

function main_pkg_fonts_ms_2_script_source(){

  echo_m "Initialise main function of fonts_ms_2 script source";

  chk_root;

  install_pkg_fonts_ms_2 "$@";

}

main_pkg_fonts_ms_2_script_source "$@";
