#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : gimp
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 26.05.2019, 20:10:38

#
#   Декларируем имя файла
#

declare -rx pkg_gimp_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_gimp_script_source)";

function install_pkg_gimp(){

  local install_pkg=(\
#   The GRAPHIKALS redaktors and STUDIOS. TOOLkit and OTHER
#
#    GIMP (GNU Image Manipulation Program) is a powerful image composition and
#    : editing program, which can be extremely useful for creating logos and other
#    : graphics for web pages. GIMP has many of the tools and filters you would expect
#    : to find in similar commercial offerings, and some interesting extras as well.
#    : GIMP provides a large image manipulation toolbox, including channel operations
#    : and layers, effects, sub-pixel imaging and anti-aliasing, and conversions, all
#    : with multi-level undo.
"gimp gimp-devel GREYCstoration-gimp gimp-data-extras gimp-dbp gimp-dds-plugin gimp-elsamuko gimp-focusblur-plugin gimp-fourier-plugin gimp-help gimp-help-ru gimp-high-pass-filter gimp-layer-via-copy-cut gimp-lensfun gimp-lqr-plugin gimp-luminosity-masks gimp-normalmap gimp-paint-studio gimp-resynthesizer gimp-save-for-web gimp-separate+ gimp-wavelet-decompose gimp-wavelet-denoise-plugin gimpfx-foundry gimp-heif-plugin" \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_pkg_gimp_script_source(){

  echo_m "Initialise main function of gimp script source";

  install_pkg_gimp "$@";

}

main_pkg_gimp_script_source "$@";
