#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : graphical_library_packs
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 12.05.2019, 4:32:53

#
#   Декларируем имя файла
#

declare -rx pkg_graphical_library_packs_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_graphical_library_packs_script_source)";


function main_pkg_graphical_library_packs_script_source(){

  echo_m "Initialise main function of graphical_library_packs script source";

  check_root;

  local install_pkg=(\
#
#   The graphical toolkit and library
#
#   A graphics library for quick creation of PNG or JPEG images
gd gd-devel \
#   The graphical toolkit for the Tcl scripting language
tk \
#   The turbojpeg package contains the TurboJPEG shared library.
turbojpeg turbojpeg-devel \
#   ImageMagick is an image display and manipulation tool for the X
#   : Window System. ImageMagick can read and write JPEG, TIFF, PNM, GIF,
#   : and Photo CD image formats. It can resize, rotate, sharpen, color
#   : reduce, or add special effects to an image, and when finished you can
#   : either save the completed work in the original format or a different
#   : one. ImageMagick also includes command line programs for creating
#   : animated or transparent .gifs, creating composite images, creating
#   : thumbnail images, and more.
ImageMagick \
#   GraphicsMagick is a comprehensive image processing package which is initially
#        : based on ImageMagick 5.5.2, but which has undergone significant re-work by
#        : the GraphicsMagick Group to significantly improve the quality and performance
#        : of the software.
GraphicsMagick \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

main_pkg_graphical_library_packs_script_source "$@";
