#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : inkscape
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 26.05.2019, 20:14:21

#
#   Декларируем имя файла
#

declare -rx pkg_inkscape_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_inkscape_script_source)";

function install_pkg_inkscape(){

  local install_pkg=(\
#   Inkscape is a vector graphics editor, with capabilities similar to
#    : Illustrator, CorelDraw, or Xara X, using the W3C standard Scalable Vector
#    : Graphics (SVG) file format.  It is therefore a very useful tool for web
#    : designers and as an interchange format for desktop publishing.
#    : Inkscape supports many advanced SVG features (markers, clones, alpha
#    : blending, etc.) and great care is taken in designing a streamlined
#    : interface. It is very easy to edit nodes, perform complex path operations,
#    : trace bitmaps and much more.
inkscape inkscape-docs inkscape-psd inkscape-view \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_pkg_inkscape_script_source(){

  echo_m "Initialise main function of inkscape script source";

  install_pkg_inkscape "$@";

}

main_pkg_inkscape_script_source "$@";
