#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : libre_office
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 12.05.2019, 22:24:56

#
#   Декларируем имя файла
#

declare -rx pkg_libre_office_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_libre_office_script_source)";


function main_pkg_libre_office_script_source(){

  echo_m "Initialise main function of libre office script source";

#
# LIBRE OFFICE
#

  local install_pkg=(\
libreoffice libreoffice-calc libreoffice-core libreoffice-data libreoffice-draw \
libreoffice-emailmerge libreoffice-filters libreoffice-graphicfilter \
libreoffice-gtk3 libreoffice-math libreoffice-opensymbol-fonts \
libreoffice-pdfimport libreoffice-pyuno libreoffice-ure libreoffice-ure-common \
libreoffice-writer libreoffice-x11 libreoffice-xsltfilter libreofficekit \
libreoffice-TexMaths libreoffice-base libreoffice-bsh \
libreoffice-gallery-vrt-network-equipment libreoffice-gdb-debug-support \
libreoffice-glade libreoffice-help-ru libreoffice-langpack-ru \
libreoffice-librelogo libreoffice-nlpsolver libreoffice-officebean \
libreoffice-officebean-common libreoffice-ogltrans libreoffice-postgresql \
libreoffice-rhino libreoffice-sdk libreoffice-sdk-doc libreoffice-voikko \
libreoffice-wiki-publisher libreoffice-writer2latex libreoffice-writer2xhtml \
libreofficekit-devel \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

main_pkg_libre_office_script_source "$@";
