#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : multimedia_library_packs
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 12.05.2019, 4:13:40

#
#   Декларируем имя файла
#

declare -rx pkg_multimedia_library_packs_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_multimedia_library_packs_script_source)";


function main_pkg_multimedia_library_packs_script_source(){

  echo_m "Initialise main function of multimedia_library_packs script source";

  check_root;

  local install_pkg=(\
# OpenAL Soft is a cross-platform software implementation of the OpenAL 3D
#            : audio API. It's built off of the open-sourced Windows version available
#            : originally from the SVN repository at openal.org. OpenAL provides
#            : capabilities for playing audio in a virtual 3d environment. Distance
#            : attenuation, doppler shift, and directional sound emitters are among
#            : the features handled by the API. More advanced effects, including air
#            : absorption, low-pass filters, and reverb, are available through the
#            : EFX extension. It also facilitates streaming audio, multi-channel buffers,
#            : and audio capture.
#
'openal-soft' 'openal-soft-devel' \
'openal-soft-qt' \
'openal-soft-examples' \
# 'openal-soft.i686' 'openal-soft-devel.i686' \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  install_pkg=(\
#   A cross-platform multimedia library
#
SDL SDL_image SDL2 SDL2-devel SDL2-static SDL2_image SDL2_image-devel SDL2_mixer SDL2_mixer-devel SDL-devel SDL-static SDL2_gfx SDL2_gfx-devel SDL2_gfx-docs SDL2_net SDL2_net-devel SDL2_ttf SDL2_ttf-devel SDL_Pango SDL_Pango-devel SDL_gfx SDL_gfx-devel SDL_image SDL_image-devel SDL_mixer SDL_mixer-devel SDL_mng SDL_mng-devel SDL_net SDL_net-devel SDL_sound SDL_sound-devel SDL_ttf SDL_ttf-devel \
# SDL.i686 SDL2.i686 SDL2-devel.i686 SDL2-static.i686 SDL2_image.i686 SDL2_image-devel.i686 SDL2_mixer.i686 SDL2_mixer-devel.i686 SDL-devel.i686 SDL-static.i686 SDL2_gfx.i686 SDL2_gfx-devel.i686 SDL2_net.i686 SDL2_net-devel.i686 SDL2_ttf.i686 SDL2_ttf-devel.i686 SDL_Pango.i686 SDL_Pango-devel.i686 SDL_gfx.i686 SDL_gfx-devel.i686 SDL_image.i686 SDL_image-devel.i686 SDL_mixer.i686 SDL_mixer-devel.i686 SDL_mng.i686 SDL_mng-devel.i686 SDL_net.i686 SDL_net-devel.i686 SDL_sound.i686 SDL_sound-devel.i686 SDL_ttf.i686 SDL_ttf-devel.i686 \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  install_pkg=(\
# Description  : libmpeg2 is a free library for decoding mpeg-2 and mpeg-1 video
# : streams. It is released under the terms of the GPL license.
'libmpeg2' \
'libmpeg2-devel' \
# Summary      : Decoder of various derivatives of MPEG standards
# URL          : http://heroinewarrior.com/libmpeg3.php3
# Лицензия     : GPLv2+
# Description  : LibMPEG3 decodes the many many derivatives of MPEG standards into
# : uncompressed data suitable for editing and playback.
# : 
# : libmpeg3 currently decodes:
# :  - MPEG-1 Layer II/III Audio and program streams
# :  - MPEG-2 Layer III Audio, program streams and transport streams
# :  - MPEG-1 and MPEG-2 Video
# :  - AC3 Audio
# :  - IFO files
# :  - VOB files
'libmpeg3' \
'libmpeg3-devel' \
'libmpeg3-utils' \
# Summary      : Libraries for the mp3Splt project
# URL          : http://mp3splt.sourceforge.net/
# Лицензия     : GPLv2
# Description  : The mp3Splt project provides utilities to split mp3 and ogg files,
# : by selecting a begin and an end time position, without decoding.
# : It is very useful to split large mp3/ogg into smaller files,
# : or to split entire albums to obtain original tracks.
# : To split an album, the split points and filenames can be selected
# : manually or automatically from CDDB (internet or a local file),
# : or from .cue files.
# : 
# : It supports automatic silence detection, which can be used
# : to adjust cddb/cue split points. It is also possible to extract
# : tracks from Mp3Wrap or AlbumWrap files in a few seconds.
# : 
# : The mp3splt project is divided in 3 parts:
# : libmp3splt, mp3splt and mp3splt-gtk.
'libmp3splt' \
'libmp3splt-devel' \
# Summary      : Library for working with files using the mp4 container format
# URL          : http://code.google.com/p/mp4v2
# Лицензия     : MPLv1.1
# Description  : The libmp4v2 library provides an abstraction layer for working with files
# : using the mp4 container format. This library is developed by mpeg4ip project
# : and is an exact copy of the library distributed in the mpeg4ip package.
'libmp4v2' \
'libmp4v2-devel' \
# Summary      : Musepack audio decoding library
# URL          : http://www.musepack.net/
# Лицензия     : BSD
# Description  : Musepack is an audio compression format with a strong emphasis on high quality.
# : It's not lossless, but it is designed for transparency, so that you won't be
# : able to hear differences between the original wave file and the much smaller
# : MPC file.
# : It is based on the MPEG-1 Layer-2 / MP2 algorithms, but has rapidly developed
# : and vastly improved and is now at an advanced stage in which it contains
# : heavily optimized and patentless code.
'libmpcdec' \
'libmpcdec-devel' \
# Summary      : Music Player Daemon Library
# URL          : http://gmpc.wikia.com/wiki/Gnome_Music_Player_Client
# Лицензия     : GPLv2+
# Description  : libmpd is an abstraction around libmpdclient. It provides an easy and
# : reliable callback based interface to mpd.
#
# 'libmpd' 'libmpd-devel' \
#
# Summary      : Library for interfacing Music Player Daemon
# URL          : http://www.musicpd.org/
# Лицензия     : BSD
# Description  : A stable, documented, asynchronous API library for interfacing MPD
# : in the C, C++ & Objective C languages.
#
# 'libmpdclient' 'libmpdclient-devel' \
#
# Summary      : Qt and QML MPRIS interface and adaptor
# URL          : https://git.merproject.org/mer-core/qtmpris
# Лицензия     : LGPLv2+
# Description  : Qt and QML MPRIS interface and adaptor.
#
# 'libmpris-qt5' 'libmpris-qt5-devel' \
#
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

main_pkg_multimedia_library_packs_script_source "$@";
