#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : nginx
## @Author : sensor-dream (SDBS)
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 09.05.2019, 6:08:46

#
#   Декларируем имя файла
#

declare -rx pkg_nginx_script_source="$BASH_SOURCE";

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Скрипт запускается из ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1;
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd "${main_run_script_path}";
        check=0;
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)";
        . "$main_project_path/main.cfg";
      fi
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_nginx_script_source)";


function install_pkg_www_initial_nginx(){

  local install_pkg=(\
'nginx' \
'nginx-all-modules' \
'nginx-mimetypes' \
'nginx-mod-http-image-filter' \
'nginx-mod-http-perl' \
'nginx-mod-http-xslt-filter' \
'nginx-mod-mail' \
'nginx-filesystem' \
'python3-certbot-nginx' \
);

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_pkg_nginx_script_source(){

  echo_m "Initialise main function";

  install_pkg_www_initial_nginx "$@";

  # echo_w "Смена nginx на nginx webtatic";

  # http://repo.webtatic.com/yum/el7/webtatic-release.rpm


}

main_pkg_nginx_script_source "$@";