#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : nginx_unit
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 10.08.2019, 23:56:32

#
#   Декларируем имя файла
#

declare -rx nginx_unit_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${nginx_unit_script_source})";

function install_nginx_unit(){

  . "${main_project_path}/pkg/repo/nginx_unit";

  local install_pkg=(\
'unit' \
'unit-api' \
'unit-api-javadoc' \
'unit-debuginfo' \
'unit-devel' \
'unit-go' \
'unit-jsc11' \
'unit-jsc11-debuginfo' \
'unit-perl' \
'unit-perl-debuginfo' \
'unit-php' \
'unit-php-debuginfo' \
'unit-python27' \
'unit-python27-debuginfo' \
'unit-python37' \
'unit-python37-debuginfo' \
'unit-ruby' \
'unit-ruby-debuginfo' \
'rubygem-rack' \
'unit-jsc-common' \
# Installing Required Software
'gcc make' \
'golang' \
'nodejs' \
'php-devel php-embedded' \
'perl-devel perl-libs' \
'python-devel' \
'ruby-devel' \
'java-1.8.0-openjdk-devel' \
'openssl-devel' \
);

  pkg -a "$@" -- "${install_pkg[*]}";

  npm install -g node-gyp;
#
 ##
  ### Control socket is located here: /var/run/unit/control.sock
 ##
#

}

function main_nginx_unit_script_source(){

  echo_m "Initialise main function of nginx_unit script source";

  install_nginx_unit "$@";

}

main_nginx_unit_script_source "$@";
