#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : other_pack
## @Author :
## @Email  :
## @Site   :
## @Date   : 23.10.2019, 3:00:15

#
#   Декларируем имя файла
#

declare -rx pkg_other_pack_script_source="$BASH_SOURCE"

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  echo "Script runs from ${main_run_script_path}"
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg"
      cd "${main_run_script_path}"
    fi
  done
fi

echo_w "Connect $(readlink -m ${pkg_other_pack_script_source})"

function install_pkg_other_pack() {

  local install_pkg=(
    binutils-powerpc64-linux-gnu binutils-powerpc64le-linux-gnu gcc-c++-powerpc64-linux-gnu gcc-c++-powerpc64le-linux-gnu gcc-powerpc64-linux-gnu gcc-powerpc64le-linux-gnu python2-powerpc-utils
  )

  # pkg -a "$@" -- "${install_pkg[*]}";

  install_pkg=(
    libva libva-utils libva-vdpau-driver vdr-vaapidevice gstreamer1-vaapi chromium-vaapi
  )

  # pkg -a "$@" -- "${install_pkg[*]}";

  install_pkg=(
    # Summary      : Efficient Probabilistic 3D Mapping Framework Based on Octrees
    # URL          : http://octomap.github.io/
    # Лицензия     : BSD and GPLv2
    # Description  : The OctoMap library implements a 3D occupancy grid mapping approach,
    # : providing data structures and mapping algorithms in C++ particularly suited
    # : for robotics. The map implementation is based on an octree.
    octomap octomap-devel octomap-octovis octomap-octovis-devel
  )

  # pkg -a "$@" -- "${install_pkg[*]}";

}

function main_pkg_other_pack_script_source() {

  echo_m "Initialise main function of other_pack script source"

  install_pkg_other_pack "$@"

}

main_pkg_other_pack_script_source "$@"
