#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : percona_mongo_db
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 11.08.2019, 15:32:15

#
#   Декларируем имя файла
#

declare -rx pkg_percona_mongo_db_script_source="$BASH_SOURCE";

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)";
  echo "Script runs from ${main_run_script_path}";
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1;
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../;
      else
        cd ${main_run_script_path};
        check=0;
        echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m";
        tput sgr0;
        exit 1;
      fi
    else
      check=0;
      declare -rx main_project_path="$(pwd)";
      . "${main_project_path}/main.cfg";
      cd "${main_run_script_path}";
    fi
  done
fi

echo_w "Connect $(readlink -m ${pkg_percona_mongo_db_script_source})";

function install_pkg_percona_mongo_db(){

  . "${main_project_path}/pkg/repo/percona_software";

  local install_pkg=(\
'Percona-Server-MongoDB' \
'Percona-Server-MongoDB-mongos' \
'Percona-Server-MongoDB-server' \
'Percona-Server-MongoDB-shell' \
'Percona-Server-MongoDB-tools' \
);

  if [[ ! -f '/etc/yum.repos.d/percona-psmdb-40-release.repo' ]]; then
    percona-release enable psmdb-40 release;
    sed -i -r "s/$releasever/${main_releasever_centos_for_dnf}/g" '/etc/yum.repos.d/percona-psmdb-40-release.repo';
    sed -i -r 's/^gpgcheck.*$/gpgcheck = 0/g' '/etc/yum.repos.d/percona-psmdb-40-release.repo';
  fi

  pkg -a "$@" -- "${install_pkg[*]}";

}

function main_pkg_percona_mongo_db_script_source(){

  echo_m "Initialise main function of percona_mongo_db script source";

  install_pkg_percona_mongo_db;

}

main_pkg_percona_mongo_db_script_source "$@";
