#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @File   : universally_unique_identifier
## @Author : sensor-dream
## @Email  : sensor-dream@sensor-dream.ru
## @Site   : https://sensor-dream.ru
## @Date   : 12.05.2019, 3:20:28

#
#   Декларируем имя файла
#

declare -rx pkg_universally_unique_identifier_script_source="$BASH_SOURCE"

if [[ -z "$main_run_script_path" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  echo "Скрипт запускается из ${main_run_script_path}"
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "$main_cfg_script_source" ]]; then
  check=1
  while [[ "$check" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd "${main_run_script_path}"
        check=0
        echo '\e[47;31m'"!!! Не найден общий файл конфигурации !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      if [[ -z "$main_cfg_script_source" ]]; then
        declare -rx main_project_path="$(pwd)"
        . "$main_project_path/main.cfg"
      fi
      cd "${main_run_script_path}"
    fi
  done
fi

echo_w "Подключаем $(readlink -m $pkg_universally_unique_identifier_script_source)"

function main_pkg_universally_unique_identifier_script_source() {

  echo_m "Initialise main function of universally_unique_identifier script source"

  check_root

  local install_pkg=(
    #   Universally Unique Identifier library
    uuid
    uuid-devel
    #   Handles uuencoding, xxencoding, yEnc, and base-64 encoding (MIME). Can do
    #        : automatic splitting of large encodes, automatic posting.  A must for
    #        : anyone serious encoding/decoding.
    uudeview
  )

  pkg -a "$@" -- "${install_pkg[*]}"

}

main_pkg_universally_unique_identifier_script_source "$@"
